version: "3.7"

services:
  db:  # https://github.com/IvoNet/docker-mysql
    container_name: db
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - 3307:${LOCAL_DB_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  backend:
    container_name: backend
    build: ./backend
    ports:
      - 8080:${LOCAL_WEBSERVER_PORT}
    depends_on:
      - "db"
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      LOCAL_WEBSERVER_PORT: ${LOCAL_WEBSERVER_PORT}
      LOCAL_DB_PORT: ${LOCAL_DB_PORT}

volumes:
  mysql-data:
